//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public int IdListPur { get; set; }
    
        public virtual List_Sale List_Sale { get; set; }
    }
}
