//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compos_Congsign
    {
        public int Id { get; set; }
        public int Id_Consigm { get; set; }
        public int Id_Compon { get; set; }
        public int Id_Counterpart { get; set; }
        public int Id_Sotrud { get; set; }
        public int Count { get; set; }
        public int Sum { get; set; }
    
        public virtual Counterparty Counterparty { get; set; }
        public virtual Сonsignment Сonsignment { get; set; }
    }
}
